function tests_ExpMap()
# Series of numerical tests on ExpMap.jl module
#


    results = Float64[]
    a = VEC3(3.0,2.0,1.0)
    b = VEC3(3.0,-1.0,2.0)
    rv = RV3(5.0,3.0,1.0)
    p = VEC6(a,rv)
    v6 = VEC6(a,b)
    # Tests R_SO3
    R = R_SO3(rv)
    rv2 = invR_SO3(R)
    res = norm((R_SO3(rv)*transpose(R_SO3(rv2)) - one(MAT3)).mat)
    push!(results, res)
    res = norm2((R*a - R_SO3(rv,a)))
    push!(results, res)
    res = norm2((R*VEC3(rv) -VEC3(rv)))
    push!(results, res)
    # Tests T_SO3
    T = T_SO3(rv)
    invT = invT_SO3(rv)
    res =norm((T*invT - one(MAT3)).mat)
    push!(results, res)
    res = norm((R - transpose(T)*invT).mat)
    push!(results, res)
    res = norm2((T*a - T_SO3(rv,a)))
    push!(results, res)
    res = norm2((T*VEC3(rv) -VEC3(rv)))
    push!(results, res)
    res = norm2((invT*a - invT_SO3(rv,a)))
    push!(results, res)
    res = norm2((invT*VEC3(rv) -VEC3(rv)))
    push!(results, res)
    # Tests derivatives of T_SO3
    res = norm((DT_SO3(rv,invT*a) + T*DinvT_SO3(rv,a)).mat)
    push!(results, res)
    res = norm((invT*DT_SO3(rv,a)+ DinvT_SO3(rv,T*a)).mat)
    push!(results, res)
    # Tests T_SE3_input_data
    r = T_SE3_input_data(p)
        pr3d(M, v)  = MAT3(M[1]*v,              M[2]*v,              M[3]*v)
        pr3dt(M, v) = MAT3(transpose(M[1])*v,   transpose(M[2])*v,   transpose(M[3])*v)
        u = a
    pr3dt(r.dT,u)  - R_SO3(rv)*(r.dTu - tilde(r.Tu)*r.T)  
    # tests H_SE3
    H = exp_SE3(p)
    p2 = log_SE3(H)
    res = norm2(log_SE3(H * exp_SE3(-p2) ))
    push!(results, res)
    # tests T_SE3
    res = norm((invT_SE3(p)*T_SE3(p) - one(MAT6)).mat)
    push!(results, res)
    res = norm2(T_SE3(p)*p -p)
    push!(results, res)
    res = norm2(invT_SE3(p)*p -p)
    push!(results, res)

    res = norm((T_SE3(r,"+")-T_SE3(p)).mat)
    push!(results, res)
    res = norm((T_SE3(r,"-")-T_SE3(-p)).mat)
    push!(results, res)
    res = norm((invT_SE3(r,"+")-invT_SE3(p)).mat)
    push!(results, res)
    res = norm((invT_SE3(r,"-")-invT_SE3(-p)).mat)
    push!(results, res)
    res = norm((invT_SE3(r,"+")*T_SE3(p) - one(MAT6)).mat)
    push!(results, res)
    res = norm((invT_SE3(r,"-")*T_SE3(-p) - one(MAT6)).mat)
    push!(results, res)
    res = norm((T_SE3(r,"+")*invT_SE3(p) - one(MAT6)).mat)
    push!(results, res)
    res = norm((Adj_SE3(H) - T_SE3(-p)*invT_SE3(p)).mat)
    push!(results, res)
    # tests derivatives of T_SE3
    Tp = T_SE3(p)
    invTp = invT_SE3(p)
    rest = norm((DT_SE3(r,invTp*v6) + Tp*DinvT_SE3(r,v6)).mat)
    push!(results, rest)
    Tm = T_SE3(-p)
    invTm = invT_SE3(-p)
    res = norm((DT_SE3(r,invTm*v6;sign_p = "-") + Tm*DinvT_SE3(r,v6;sign_p = "-")).mat) # vérifier
    push!(results, res)
    res = norm((DT_SE3(r,transpose(invTp)*v6;trp=true) + transpose(Tp)*DinvT_SE3(r,v6;trp=true)).mat)
    push!(results, res)
    res = norm((DT_SE3(r,transpose(invTm)*v6;trp=true,sign_p = "-") + transpose(Tm)*DinvT_SE3(r,v6;trp=true,sign_p = "-")).mat)
    push!(results, res) 
    # println("number of tests = ", length(results))
    # println("cumulated norm of results = ", norm(results))
    return norm(results)
end